

TRUNCATE TABLE "MovieClasses" RESTART IDENTITY;

INSERT INTO "MovieClasses" ("Title", "ReleaseDate", "Director", "Genre") VALUES ('The Shawshank Redemption', '1994-09-23', 'Frank Darabont', 'Drama');
INSERT INTO "MovieClasses" ("Title", "ReleaseDate", "Director", "Genre") VALUES ('The Godfather', '1972-03-24', 'Francis Ford Coppola', 'Crime');
INSERT INTO "MovieClasses" ("Title", "ReleaseDate", "Director", "Genre") VALUES ('The Dark Knight', '2008-07-18', 'Christopher Nolan', 'Action');
INSERT INTO "MovieClasses" ("Title", "ReleaseDate", "Director", "Genre") VALUES ('Pulp Fiction', '1994-10-14', 'Quentin Tarantino', 'Crime');
INSERT INTO "MovieClasses" ("Title", "ReleaseDate", "Director", "Genre") VALUES ('Schindler''s List', '1993-12-15', 'Steven Spielberg', 'Biography');
INSERT INTO "MovieClasses" ("Title", "ReleaseDate", "Director", "Genre") VALUES ('The Lord of the Rings: The Return of the King', '2003-12-17', 'Peter Jackson', 'Adventure');
INSERT INTO "MovieClasses" ("Title", "ReleaseDate", "Director", "Genre") VALUES ('Fight Club', '1999-10-15', 'David Fincher', 'Drama');
INSERT INTO "MovieClasses" ("Title", "ReleaseDate", "Director", "Genre") VALUES ('Forrest Gump', '1994-07-06', 'Robert Zemeckis', 'Drama');
INSERT INTO "MovieClasses" ("Title", "ReleaseDate", "Director", "Genre") VALUES ('Inception', '2010-07-16', 'Christopher Nolan', 'Action');
INSERT INTO "MovieClasses" ("Title", "ReleaseDate", "Director", "Genre") VALUES ('The Matrix', '1999-03-31', 'Lana and Lilly Wachowski', 'Sci-Fi');
INSERT INTO "MovieClasses" ("Title", "ReleaseDate", "Director", "Genre") VALUES ('The Silence of the Lambs', '1991-02-14', 'Jonathan Demme', 'Thriller');
INSERT INTO "MovieClasses" ("Title", "ReleaseDate", "Director", "Genre") VALUES ('Se7en', '1995-09-22', 'David Fincher', 'Crime');
INSERT INTO "MovieClasses" ("Title", "ReleaseDate", "Director", "Genre") VALUES ('Gladiator', '2000-05-05', 'Ridley Scott', 'Action');
INSERT INTO "MovieClasses" ("Title", "ReleaseDate", "Director", "Genre") VALUES ('Braveheart', '1995-05-24', 'Mel Gibson', 'Biography');
INSERT INTO "MovieClasses" ("Title", "ReleaseDate", "Director", "Genre") VALUES ('Jurassic Park', '1993-06-11', 'Steven Spielberg', 'Adventure');
INSERT INTO "MovieClasses" ("Title", "ReleaseDate", "Director", "Genre") VALUES ('Titanic', '1997-12-19', 'James Cameron', 'Romance');
INSERT INTO "MovieClasses" ("Title", "ReleaseDate", "Director", "Genre") VALUES ('Goodfellas', '1990-09-19', 'Martin Scorsese', 'Crime');
INSERT INTO "MovieClasses" ("Title", "ReleaseDate", "Director", "Genre") VALUES ('The Departed', '2006-10-06', 'Martin Scorsese', 'Crime');
INSERT INTO "MovieClasses" ("Title", "ReleaseDate", "Director", "Genre") VALUES ('Avatar', '2009-12-18', 'James Cameron', 'Sci-Fi');
INSERT INTO "MovieClasses" ("Title", "ReleaseDate", "Director", "Genre") VALUES ('Saving Private Ryan', '1998-07-24', 'Steven Spielberg', 'War');
INSERT INTO "MovieClasses" ("Title", "ReleaseDate", "Director", "Genre") VALUES ('Interstellar', '2014-11-07', 'Christopher Nolan', 'Sci-Fi');
INSERT INTO "MovieClasses" ("Title", "ReleaseDate", "Director", "Genre") VALUES ('The Green Mile', '1999-12-10', 'Frank Darabont', 'Crime');
INSERT INTO "MovieClasses" ("Title", "ReleaseDate", "Director", "Genre") VALUES ('The Lion King', '1994-06-24', 'Roger Allers, Rob Minkoff', 'Animation');
INSERT INTO "MovieClasses" ("Title", "ReleaseDate", "Director", "Genre") VALUES ('Back to the Future', '1985-07-03', 'Robert Zemeckis', 'Adventure');
INSERT INTO "MovieClasses" ("Title", "ReleaseDate", "Director", "Genre") VALUES ('Star Wars: Episode IV - A New Hope', '1977-05-25', 'George Lucas', 'Sci-Fi');
INSERT INTO "MovieClasses" ("Title", "ReleaseDate", "Director", "Genre") VALUES ('The Avengers', '2012-05-04', 'Joss Whedon', 'Action');
INSERT INTO "MovieClasses" ("Title", "ReleaseDate", "Director", "Genre") VALUES ('Iron Man', '2008-05-02', 'Jon Favreau', 'Action');
INSERT INTO "MovieClasses" ("Title", "ReleaseDate", "Director", "Genre") VALUES ('Spider-Man: Into the Spider-Verse', '2018-12-14', 'Bob Persichetti, Peter Ramsey, Rodney Rothman', 'Animation');
INSERT INTO "MovieClasses" ("Title", "ReleaseDate", "Director", "Genre") VALUES ('Black Panther', '2018-02-16', 'Ryan Coogler', 'Action');
INSERT INTO "MovieClasses" ("Title", "ReleaseDate", "Director", "Genre") VALUES ('Deadpool', '2016-02-12', 'Tim Miller', 'Action');
INSERT INTO "MovieClasses" ("Title", "ReleaseDate", "Director", "Genre") VALUES ('Guardians of the Galaxy', '2014-08-01', 'James Gunn', 'Action');
INSERT INTO "MovieClasses" ("Title", "ReleaseDate", "Director", "Genre") VALUES ('Wonder Woman', '2017-06-02', 'Patty Jenkins', 'Action');
INSERT INTO "MovieClasses" ("Title", "ReleaseDate", "Director", "Genre") VALUES ('Thor: Ragnarok', '2017-11-03', 'Taika Waititi', 'Action');
INSERT INTO "MovieClasses" ("Title", "ReleaseDate", "Director", "Genre") VALUES ('Doctor Strange', '2016-11-04', 'Scott Derrickson', 'Action');
INSERT INTO "MovieClasses" ("Title", "ReleaseDate", "Director", "Genre") VALUES ('Star Wars: Episode V - The Empire Strikes Back', '1980-05-21', 'Irvin Kershner', 'Sci-Fi');
INSERT INTO "MovieClasses" ("Title", "ReleaseDate", "Director", "Genre") VALUES ('Star Wars: Episode VI - Return of the Jedi', '1983-05-25', 'Richard Marquand', 'Sci-Fi');
INSERT INTO "MovieClasses" ("Title", "ReleaseDate", "Director", "Genre") VALUES ('Incredibles 2', '2018-06-15', 'Brad Bird', 'Animation');
INSERT INTO "MovieClasses" ("Title", "ReleaseDate", "Director", "Genre") VALUES ('The Incredibles', '2004-11-05', 'Brad Bird', 'Animation');
INSERT INTO "MovieClasses" ("Title", "ReleaseDate", "Director", "Genre") VALUES ('Finding Nemo', '2003-05-30', 'Andrew Stanton', 'Animation');
INSERT INTO "MovieClasses" ("Title", "ReleaseDate", "Director", "Genre") VALUES ('Toy Story', '1995-11-22', 'John Lasseter', 'Animation');
INSERT INTO "MovieClasses" ("Title", "ReleaseDate", "Director", "Genre") VALUES ('Toy Story 3', '2010-06-18', 'Lee Unkrich', 'Animation');
INSERT INTO "MovieClasses" ("Title", "ReleaseDate", "Director", "Genre") VALUES ('Inside Out', '2015-06-19', 'Pete Docter, Ronnie del Carmen', 'Animation');
INSERT INTO "MovieClasses" ("Title", "ReleaseDate", "Director", "Genre") VALUES ('Coco', '2017-11-22', 'Lee Unkrich, Adrian Molina', 'Animation');
INSERT INTO "MovieClasses" ("Title", "ReleaseDate", "Director", "Genre") VALUES ('Monsters, Inc.', '2001-11-02', 'Pete Docter, David Silverman, Lee Unkrich', 'Animation');
INSERT INTO "MovieClasses" ("Title", "ReleaseDate", "Director", "Genre") VALUES ('WALL-E', '2008-06-27', 'Andrew Stanton', 'Animation');
INSERT INTO "MovieClasses" ("Title", "ReleaseDate", "Director", "Genre") VALUES ('Up', '2009-05-29', 'Pete Docter, Bob Peterson', 'Animation');